tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "thoughtbot/formulae"
tap "universal-ctags/universal-ctags"

brew "asdf"
brew "exa"
brew "fzf"
brew "gh"
brew "git-delta"
brew "gnupg"
brew "graphviz"
brew "jq"
brew "neovim"
brew "redis", restart_service: true
brew "ripgrep"
brew "spotify-tui"
brew "starship"
brew "thoughtbot/formulae/rcm"
brew "tmux"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
brew "wget"
brew "zsh-completions"

cask "font-fira-code"
cask "gpg-suite-no-mail"
cask "iterm2"
