tap "homebrew/cask-fonts"
tap "thoughtbot/formulae"

brew "asdf"
brew "coreutils"
brew "eza"
brew "fzf"
brew "gh"
brew "git-absorb"
brew "git-delta"
brew "gpg"
brew "jq"
brew "neovim"
brew "ripgrep"
brew "starship"
brew "thoughtbot/formulae/rcm"
brew "tmux"
brew "zsh-completions"

cask "amethyst"
cask "wezterm"
cask "docker"
cask "1password"
cask "obsidian"
