#!/usr/bin/env bash

set -e

HOMEBREW_INSTALL_SCRIPT="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
RUST_INSTALL_SCRIPT="https://sh.rustup.rs"

install_homebrew() {
  if command -v brew &> /dev/null; then
    echo "Homebrew already installed"	
  else
    echo "Installing Homebrew"	
    /bin/bash -c "$(curl -fsSL $HOMEBREW_INSTALL_SCRIPT)"
  fi
}

install_rust() {
  if command -v rustc &> /dev/null; then
    echo "Rust already installed"	
  else
    echo "Installing Rust"	
    curl --proto '=https' --tlsv1.2 -sSf "$RUST_INSTALL_SCRIPT" | sh
  fi
}

install_rcm() {
  if command -v rcup &> /dev/null; then
    echo "rcm already installed"	
  else
    echo "Installing rcm"	
    brew install rcm
  fi
}

dotfiles_config_up() {
  rcup -v rcrc
}

brewfile_up() {
  rcup -v Brewfile
}

brew_bundle_up() {
  brew bundle install
}

setup_localrc() {
  touch ~/.localrc
}

install_nvim_dependencies() {
  asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
  asdf plugin add python https://github.com/asdf-community/asdf-python
  asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
  asdf plugin add golang https://github.com/asdf-community/asdf-golang.git

  rcup -v tool-versions

  asdf install

  python3 -m pip install --user --upgrade pynvim
  gem install neovim
  npm install -g neovim
}

dotfiles_all_up() {
  rcup -v
}

main() {
  setup_localrc
  install_homebrew
  install_rust
  install_rcm
  dotfiles_config_up
  brewfile_up
  brew_bundle_up
  install_nvim_dependencies
  dotfiles_all_up
}

main
