#!/usr/bin/env bash

set -e

HOMEBREW_INSTALL_SCRIPT="https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
RUST_INSTALL_SCRIPT="https://sh.rustup.rs"

# TODO: Make idempotent
# TODO: ASDF for ruby/python/node
# TODO: Install go as well for go tools I'm building

install_homebrew() {
  /bin/bash -c "$(curl -fsSL $HOMEBREW_INSTALL_SCRIPT)"
}

install_rust() {
  curl --proto '=https' --tlsv1.2 -sSf "$RUST_INSTALL_SCRIPT" | sh
}

install_rcm() {
  brew install rcm
}

dotfiles_config_up() {
  rcup rcrc
}

brewfile_up() {
  rcup Brewfile
}

brew_bundle_up() {
  brew bundle install
}

dotfiles_all_up() {
  rcup -v
}

# 1. Install latest `python3` and `nodejs` LTS using asdf
#     - `asdf plugin add python`
#     - `asdf plugin add nodejs`
#     - `rcup tool-versions`
#     - `asdf install`
# 1. Install python3 and nodejs providers for neovim
#     - See `:checkhealth provider` in `neovim`
#     - `pip3 install --user --upgrade pynvim`
#     - `npm install -g neovim`
# 1. Symlink the rest of the dotfiles
#     - `rcup -v`
main() {
  install_homebrew
  install_rust
  install_rcm
  dotfiles_config_up
  brewfile_up
  brew_bundle_up
  dotfiles_all_up
}

main
